### ISSUE TITLE
دیتاست

### ISSUE THREAD

**Issue by Ebimsv** [AminTaheri23/Deep-Persian-NER#1]
اگه امکانش هست دیتاستی که باهاش کار کردی رو به اشتراک بزاری، آخه اون پیجی که لینکش رو گذاشتی چند تا فایله و بنظر میاد داده هاش تکراری هستند.
@AminTaheri23

**Comment by AminTaheri23** [comment]
سلام

دیتاست اضافه شد . من ایشو رو میبندم. اگر مشکلی بود دوباره بازش کنید.

سپاس
